import { z } from "zod";

// ─── User context (built during onboarding) ───────────────────────────────────

export const UserContextSchema = z.object({
  name: z.string().optional(),
  role: z.string().describe("Professional role (founder, marketer, engineer, etc.)"),
  industry: z.string().describe("Industry or niche"),
  topics: z.array(z.string()).describe("Main topics to write about"),
  voice: z.string().describe("Voice description — e.g. 'direct, analytical, no corporate speak'"),
  audienceDescription: z.string().describe("Who the content is for"),
  contentGoals: z.array(z.string()).describe("What content should achieve"),
  excludeTopics: z.array(z.string()).optional().default([]).describe("Topics to avoid"),
  platforms: z.array(z.string()).describe("Publishing platforms: linkedin, x, blog, newsletter, medium"),
});

export type UserContext = z.infer<typeof UserContextSchema>;

export const TypedMemorySchema = z.object({
  voiceExamples: z.array(z.string()).default([]),
  styleRules: z.array(z.string()).default([]),
  audienceInsights: z.array(z.string()).default([]),
  doNotSay: z.array(z.string()).default([]),
  successfulPosts: z.array(z.string()).default([]),
  campaignContext: z.array(z.string()).default([]),
  sourcePreferences: z.array(z.string()).default([]),
});

export type TypedMemory = z.infer<typeof TypedMemorySchema>;

export const WorkspaceMetadataSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string().default(""),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export type WorkspaceMetadata = z.infer<typeof WorkspaceMetadataSchema>;

// ─── RSS feed item ────────────────────────────────────────────────────────────

export const RssItemSchema = z.object({
  id: z.string(),
  source: z.string(),
  title: z.string(),
  link: z.string(),
  snippet: z.string(),
  publishedAt: z.string().optional(),
});

export type RssItem = z.infer<typeof RssItemSchema>;

// ─── Enriched article (what quillby_fetch_articles returns to the host) ─────────
// The host model reads these and does its own relevance scoring + card generation.

export const EnrichedArticleSchema = z.object({
  id: z.string(),
  source: z.string(),
  title: z.string(),
  link: z.string(),
  snippet: z.string(),
  enrichedContent: z.string().describe("Full article text extracted from the URL, up to 6000 chars"),
  publishedAt: z.string().optional(),
});

export type EnrichedArticle = z.infer<typeof EnrichedArticleSchema>;

// ─── Structure card ───────────────────────────────────────────────────────────
// Cards are generated by the HOST model, then saved via quillby_save_cards.
// All fields except title/source/link/thesis are optional to accommodate
// hosts that provide varying levels of analysis.

export const CardInputSchema = z.object({
  title: z.string(),
  source: z.string(),
  link: z.string(),
  thesis: z.string().describe("Core insight in one sentence"),
  relevanceScore: z.number().min(0).max(10).optional().default(0),
  relevanceReason: z.string().optional().default(""),
  keyInsights: z.array(z.string()).optional().default([]),
  insightOptions: z.array(z.string()).optional().default([]),
  takeOptions: z.array(z.string()).optional().default([]),
  angleOptions: z.array(z.string()).optional().default([]),
  hookOptions: z.array(z.string()).optional().default([]),
  wireframeOptions: z.array(z.string()).optional().default([]),
  trendTags: z.array(z.string()).optional().default([]),
  transposabilityHint: z.string().optional().default(""),
});

export type CardInput = z.infer<typeof CardInputSchema>;

export const StructureCardSchema = CardInputSchema.extend({
  id: z.number(),
  references: z.array(z.string()),
});

export type StructureCard = z.infer<typeof StructureCardSchema>;

// ─── Harvest bundle ───────────────────────────────────────────────────────────

export const CurationStatusSchema = z.enum(["shortlisted", "approved", "skipped"]);
export type CurationStatus = z.infer<typeof CurationStatusSchema>;

export const HarvestBundleSchema = z.object({
  generatedAt: z.string(),
  dateLabel: z.string(),
  cards: z.array(StructureCardSchema),
  /** Map of cardId (as string) → curation status. Set by quillby_curate_card. */
  curationState: z.record(z.string(), CurationStatusSchema).optional().default({}),
});

export type HarvestBundle = z.infer<typeof HarvestBundleSchema>;

// ─── Draft ────────────────────────────────────────────────────────────────────

export const DraftSchema = z.object({
  platform: z.string(),
  content: z.string(),
  cardId: z.number().optional(),
});

export type Draft = z.infer<typeof DraftSchema>;
